# -*- coding: utf-8 -*-
"""DadosEJA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/edsonribferreira/Dashboard_EJA_EPT/blob/main/DadosEJA.ipynb
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import os
from streamlit_gsheets import GSheetsConnection

ARQUIVO_PRINCIPAL = 'dados_eja_completo.csv'
st.set_page_config(page_title="Dashboard EJA IFF Livre", layout="wide")

# --- FUNÇÕES DE DADOS ---
def salvar_dados(novo_df):
    if os.path.exists(ARQUIVO_PRINCIPAL):
        novo_df.to_csv(ARQUIVO_PRINCIPAL, mode='a', header=False, index=False)
    else:
        novo_df.to_csv(ARQUIVO_PRINCIPAL, index=False)

st.title("📊 Painel de Dados - Programa EJAEPT - IFF")

# --- ÁREA DE UPLOAD ---
with st.expander("⬆️ Alimentar Base de Dados"):
    novo_arquivo = st.file_uploader("Suba o CSV com os dados", type=['csv'])
    
    if novo_arquivo:
        df_temp = pd.read_csv(novo_arquivo)
        colunas_csv = list(df_temp.columns)
        
        st.write("### ⚙️ Mapeamento de Colunas")
        st.info("Verifique se o sistema conectou as colunas do seu arquivo corretamente:")
        
        # Colunas que o seu dashboard exige
        colunas_obrigatorias = ['nome_estudante', 'curso', 'campus', 'municipio', 'bairro', 'etnia', 'renda', 'sexo']
        
        # Função para tentar adivinhar a coluna baseada em palavras-chave
        def adivinhar_coluna(padrao, col_disponiveis):
            dicas = {
                'nome_estudante': ['nome', 'aluno', 'completo'], 'curso': ['curso'], 'campus': ['campus', 'polo'],
                'municipio': ['município', 'cidade'], 'bairro': ['bairro'], 'etnia': ['etnia', 'cor', 'raça'],
                'renda': ['renda'], 'sexo': ['sexo', 'gênero']
            }
            for col in col_disponiveis:
                if any(dica in col.lower() for dica in dicas.get(padrao, [])):
                    return col
            return "❌ Não existe no arquivo"

        mapa_colunas = {}
        valores_padrao = {}
        
        # Cria a interface de mapeamento
        for col_padrao in colunas_obrigatorias:
            opcoes = ["❌ Não existe no arquivo"] + colunas_csv
            palpite = adivinhar_coluna(col_padrao, colunas_csv)
            
            c1, c2 = st.columns([1, 1])
            with c1:
                # O usuário escolhe qual coluna do CSV corresponde à coluna do Dashboard
                escolha = st.selectbox(f"Coluna para **{col_padrao.upper()}**:", options=opcoes, index=opcoes.index(palpite))
                mapa_colunas[col_padrao] = escolha
            
            with c2:
                # Se não existir (ex: curso e campus), abre um campo para digitar o valor fixo
                if escolha == "❌ Não existe no arquivo":
                    valores_padrao[col_padrao] = st.text_input(f"Digite o valor para todas as linhas:", key=f"txt_{col_padrao}", placeholder="Ex: Libras")
                else:
                    st.write("") # Apenas para alinhar o layout
                    
        if st.button("Confirmar Mapeamento e Salvar Dados"):
            df_final = pd.DataFrame()
            
            # Monta a tabela final padronizada baseada nas escolhas
            for col_padrao in colunas_obrigatorias:
                escolha = mapa_colunas[col_padrao]
                if escolha == "❌ Não existe no arquivo":
                    df_final[col_padrao] = valores_padrao.get(col_padrao, "Não Informado")
                else:
                    df_final[col_padrao] = df_temp[escolha]
                    
            salvar_dados(df_final)
            st.success("Dados padronizados e integrados à base principal com sucesso!")

# --- ÁREA DE TESTES E CONFIGURAÇÕES ---
st.sidebar.divider()
st.sidebar.subheader("⚙️ Zona de Testes")

if st.sidebar.button("🗑️ Apagar Base de Dados (Reset)"):
    if os.path.exists(ARQUIVO_PRINCIPAL):
        os.remove(ARQUIVO_PRINCIPAL)
        st.sidebar.success("Arquivo de dados removido com sucesso!")
        # Força o Streamlit a recarregar a página para atualizar o dashboard
        st.rerun()
    else:
        st.sidebar.info("Não há dados para apagar.")

# --- APLICAÇÃO PRINCIPAL ---
if os.path.exists(ARQUIVO_PRINCIPAL):
    df = pd.read_csv(ARQUIVO_PRINCIPAL)

    # Remover colunas que não fazem sentido para agrupamento/gráficos (ex: nome)
    colunas_analise = [col for col in df.columns if col not in ['nome_estudante']]

    # --- 1. FILTROS GLOBAIS (BARRA LATERAL) ---
    st.sidebar.header("🔍 Filtros Globais")
    st.sidebar.write("Filtre a base antes de gerar o gráfico:")
    df_filtrado = df.copy()

    # Cria um filtro dinâmico para cada coluna do dataframe
    for col in colunas_analise:
        valores_unicos = df[col].dropna().unique()
        selecao = st.sidebar.multiselect(f"{col.capitalize()}", options=valores_unicos, default=[])
        if selecao:
            df_filtrado = df_filtrado[df_filtrado[col].isin(selecao)]

    # --- 2. CONSTRUTOR LIVRE DE GRÁFICOS ---
    st.header("🛠️ Construtor de Gráficos")

    c1, c2, c3 = st.columns(3)
    with c1:
        eixo_x = st.selectbox("1. Escolha a Categoria Principal (Eixo X):", colunas_analise)
    with c2:
        divisao_cor = st.selectbox("2. Cruzar com (Subdivisão/Cor):", ['Nenhum'] + colunas_analise)
    with c3:
        tipo_grafico = st.selectbox("3. Tipo de Gráfico:", ["Barras Agrupadas", "Barras Empilhadas", "Pizza / Donut"])

    st.divider()

    # --- 3. LÓGICA DE GERAÇÃO DO GRÁFICO ---
    if len(df_filtrado) == 0:
        st.warning("Nenhum dado encontrado para os filtros selecionados.")
    else:
        st.write(f"**Analisando {len(df_filtrado)} registros filtrados.**")

        # Cenário 1: Cruzando duas colunas (Ex: Curso vs Renda)
        if divisao_cor != 'Nenhum':
            # Agrupa e conta a quantidade
            df_agrupado = df_filtrado.groupby([eixo_x, divisao_cor]).size().reset_index(name='Quantidade')

            if tipo_grafico == "Barras Agrupadas":
                fig = px.bar(df_agrupado, x=eixo_x, y='Quantidade', color=divisao_cor, barmode='group')
            elif tipo_grafico == "Barras Empilhadas":
                fig = px.bar(df_agrupado, x=eixo_x, y='Quantidade', color=divisao_cor)
            else: # Pizza não suporta bem cruzamento duplo natural sem facets, mas podemos fazer um Sunburst ou Pizza simples do agrupamento
                fig = px.sunburst(df_agrupado, path=[eixo_x, divisao_cor], values='Quantidade')

        # Cenário 2: Analisando apenas uma coluna (Ex: Apenas Etnia)
        else:
            df_agrupado = df_filtrado[eixo_x].value_counts().reset_index()
            df_agrupado.columns = [eixo_x, 'Quantidade']

            if tipo_grafico in ["Barras Agrupadas", "Barras Empilhadas"]:
                fig = px.bar(df_agrupado, x=eixo_x, y='Quantidade', color=eixo_x)
            else:
                fig = px.pie(df_agrupado, names=eixo_x, values='Quantidade', hole=0.4)

        # Exibe o gráfico gerado
        st.plotly_chart(fig, use_container_width=True)

    # --- 4. TABELA DE DADOS RAW ---
    with st.expander("Ver Tabela de Dados Filtrados"):
        st.dataframe(df_filtrado)

else:
    st.info("Nenhum dado no sistema. Faça o upload do primeiro arquivo CSV.")

# --- RODAPÉ EM TEXTO DISCRETO ---
rodape_html = """
    <div style="text-align: center; color: #888888; font-size: 12px; margin-top: 30px; padding-bottom: 20px;">
        <p style="margin: 0; line-height: 1.4;">
            <b>💻Desenvolvido por Edson Ferreira - 2026</b><br>           
             Estudante de Análise e Desenvolvimento de Sistemas - PUCPR<br>
            📧 edsonferreira.dev@gmail.com
        </p>
    </div>
    """
st.markdown(rodape_html, unsafe_allow_html=True)
